library(rpart)
library(e1071)
library(rpart.plot)
library(caret)
data<-readxl::read_excel("epl.xls")
teamdata= aggregate(data[c(14,16,19,20,22)],by=list(data$Team,data$Opposition,data$Venue),sum)
fitControl<- trainControl(method="CV",number = 5)
cartGrid<-expand.grid(.cp=(1:50)*0.01)
main_tree<-rpart(teamdata$Goals~+teamdata$Group.3+teamdata$`Shots On Target inc goals`+teamdata$`Key Passes`,data = teamdata,control = rpart.control(cp=0.01))
prp(main_tree)
match_model<-lm(Goals~Group.3+`Shots On Target inc goals`+`Total Successful Passes All`+`Key Passes`,data=teamdata)
summary(teamdata)
plot(match_model)
